sonar.projectKey=nangman-web
sonar.projectName=nangman-infra-web

sonar.sources=frontend,backend
sonar.tests=frontend,backend
sonar.exclusions=**/*.spec.ts,**/*.spec.tsx,**/node_modules/**,**/.next/**,**/dist/**,**/public/**,**/coverage/**,**/scripts/**
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/public/**,**/coverage/**,**/scripts/**
sonar.coverage.exclusions=\
frontend/app/HomeClient.tsx,\
frontend/app/members/page.tsx,\
frontend/components/features/**/*.tsx,\
frontend/components/icons/GitHubIcon.tsx,\
frontend/components/layout/Header.tsx,\
frontend/components/members/MemberCard.tsx,\
frontend/components/members/ProfileModal.tsx,\
frontend/components/monitoring/**/*,\
frontend/components/services/ServiceCard.tsx,\
frontend/components/ui/dialog.tsx,\
frontend/lib/logger/*.ts,\
backend/src/common/logger/logger.config.ts,\
backend/src/modules/members/infrastructure/pdf/**/*.ts,\
backend/src/modules/monitoring/infrastructure/collectors/**/*.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/app/globals.css
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.e2.resourceKey=backend/src/main.ts
sonar.sourceEncoding=UTF-8
