sonar.projectKey=nangman-web
sonar.projectName=nangman-infra-web

sonar.sources=frontend,backend
sonar.tests=frontend,backend
sonar.exclusions=**/*.spec.ts,**/*.spec.tsx,**/node_modules/**,**/.next/**,**/dist/**,**/public/**,**/coverage/**,**/scripts/**
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/public/**,**/coverage/**,**/scripts/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/app/globals.css
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.e2.resourceKey=backend/src/main.ts
sonar.sourceEncoding=UTF-8
