sonar.projectKey=nangman-web
sonar.projectName=nangman-infra-web

sonar.sources=frontend,backend
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/public/**,**/coverage/**,**/scripts/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
